# Project configuration
# dataset: 'cifar10' (matches Cars/Birds/Cats/Deer/Dog/Frog/Horses/Ships/Trucks/Airplanes)
#          'fashion_mnist' (baseline 28x28 grayscale clothing items, 60k train)
dataset: cifar10

# Training hyperparameters
seed: 42
epochs: 20
batch_size: 64
learning_rate: 0.001

# Data augmentation
augment:
  flip: true
  rotate: 0.05      # radians, ~2.8 degrees
  zoom: 0.1
  contrast: 0.1

# Callbacks
early_stopping_patience: 5
reduce_lr_patience: 2
reduce_lr_factor: 0.5

# Paths
models_dir: models
outputs_dir: outputs
logs_dir: logs
